### ISSUE TITLE
Invalid sets for main/sub combination don't fail gracefully

### ISSUE THREAD

**Issue by Arkevorkhat1** [ThornyFFXI/LuAshitacast#32]
I wrote up my COR lua based on the included guides, and when I tried today to run COR/WAR instead of my usual COR/DNC, I got a stream of errors relating to my off-hand in the lua. 

I can see two major directions a fix for this could go. One being having the addon watch for errors like that and stop trying to equip offhands on main/sub combinations that don't have DW, and the other being the option to have MAIN_SUB.lua files to gate off invalid configurations for other subjobs.

**Comment by ThornyFFXI** [comment]
There are already near limitless ways to design your file such that you don't try to equip an offhand with a sub that doesn't support it.  You can use gData checks to branch what weapons should be equipped, very easily.  I do not consider this a bug.

**Comment by Arkevorkhat1** [comment]
Alright then. I'll add it to my own version then, and keep it to myself, since this is apparently intended behavior.
![image](https://github.com/ThornyFFXI/LuAshitacast/assets/136962969/a07aeb7d-a94f-46e0-a3fd-57c21582e2e8)

**Comment by ThornyFFXI** [comment]
Intended behavior is for you to write a statement to check your subjob and equip something appropriate. 
Giving me attitude to complain about a mistake on your end, in free software, is silly.

If you would rather edit the core than your own profile, you are certainly welcome to do that, as it has a very permissive license.  However, the included data functions include easy ways to check your subjob, and you could use those to equip different items, or force another file to load.

The only appropriate solution for the core that I would approve in my repo is to handle all weapon and item displacement internally.  The amount of corner cases for preemptively handling weapon swaps is not small, especially when you factor in precast/midcast swaps occuring faster than c<>s communication updates your gear from precast.  So, while it is something that may happen in the future, I am not going to push a half fix just because you deem it more appropriate than correcting your own file.
