### ISSUE TITLE
OnLoad does not execute when loading addon

### ISSUE THREAD

**Issue by Sippius** [ThornyFFXI/LuAshitacast#6]
profile.OnLoad does not execute when using /addon load or /addon reload . Is that expected?
Executes fine with /lac reload and when changing jobs.

**Comment by ThornyFFXI** [comment]
Can you give an example of the OnLoad code that isn't executing?  Having difficulty reproducing this one.

**Comment by ThornyFFXI** [comment]
For additional clarification, addon load will look for a profile in the format:
Ashita/config/addons/luashitacast/Name_ID/JOB.lua

then, it will look for the format:
Ashita/config/addons/luashitacast/Name_JOB.lua

If either is found, it should load them and execute the onload events.  If luashitacast is on autoload, that will occur when you select a character as you do not initially have a character name until you log in.  OnLoad seems to trigger correctly for me in both cases, if that is not the case I suspect it may be something related to the contents of the OnLoad event.

**Comment by Sippius** [comment]
It is my issue. Apologies for the inconvenience. I thought I had tested with the default Name_ID/JOB.lua, but apparently I didn't.

I have been running a single config for all jobs on a character. I did this with ashitacast to avoid replication of some  light automation that I am mostly migrating to my own addons in v4. Anyway, I was using the chat manager to call /lac load within OnLoad. Turns out that is a bad idea which makes sense. If I call gState.LoadProfileEx directly within OnLoad, it works as expected. There are a couple other ways I can get similar results that I may switch to. I'm still playing around to figure out what works for me.

**Comment by ThornyFFXI** [comment]
If your goal was to have a profile for each job that does nothing besides loading the other jobs' profile, you could best accomplish it by using something along the lines of:

`return gFunc.LoadFile('alljobs.lua');`

You would still need to actually load alljobs.lua to use addset, but this would avoid potential problems caused by calling load from OnLoad, as it would hand over the full file without triggering another load.

A more practical approach would probably be to avoid any automation within LuAshitacast and isolate it to addons.  If there is a distinct reason to tie something to LAC, you can use loadfile, require, or gFunc.LoadFile to load in extra lua documents that multiple profiles will require.

**Comment by Sippius** [comment]
Thanks for the suggestion. I'll move over to just returning with gFunc.LoadFile for now. I was unaware of gFunc.LoadFile until you released your helper function. I am by no means an accomplished programmer and lua is new to me. :) I can normally manage to brute force my way through, but it is often not as elegant as it could be.

I tried using loadfile earlier, but was not successful. I expect I was using it wrong. I did manage to get require working. As a note, it was not as simple as just using require. The config directory is not in the search path and had to be added for it to find the file (something you probably already know).

The majority of my automation is being moved to separate addons now. The switch to ashita v4 and lua based ashitacast was the bump I needed to better understand lua. Most of what I have is simple scripts with arguments so not difficult to move over.

Thanks again!
